global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sketchdojo-monitor'

rule_files:
  - "alerts/*.yml"

scrape_configs:
  - job_name: 'sketchdojo-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
