# =============================================================================
# docker/docker-compose.dev.yml
# =============================================================================
version: '3.8'

services:
  # API Service (Development)
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=mysql+asyncmy://sketchdojo:password@mysql:3306/sketchdojo
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - DEBUG=true
    depends_on:
      - mysql
      - redis
    volumes:
      - ..:/app
      - ./storage:/app/storage
    networks:
      - sketchdojo-network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker (Development)
  celery-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A app.core.celery_app worker --loglevel=debug --reload
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=mysql+asyncmy://sketchdojo:password@mysql:3306/sketchdojo
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - mysql
      - redis
    volumes:
      - ..:/app
      - ./storage:/app/storage
    networks:
      - sketchdojo-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sketchdojo
      - MYSQL_USER=sketchdojo
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sketchdojo-network
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - sketchdojo-network
    restart: unless-stopped

  # Redis Insight (Development Tool)
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - sketchdojo-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  sketchdojo-network:
    driver: bridge

