version: '3.8'

services:
  worker:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.worker
    volumes:
      - ../storage:/app/storage
      - ../logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./sketchdojo.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - ENVIRONMENT=development
      - DEBUG=true
      - SKETCHDOJO_SETTINGS_MODULE=docker.docker-settings
      # JWT authentication settings
      - SECRET_KEY=${SECRET_KEY:-development_secret_key}
      - JWT_SECRET=${JWT_SECRET:-development_jwt_secret}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION=1440  # 24 hours in minutes
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
