# =============================================================================
# deployment/kubernetes/api-deployment.yaml
# =============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sketchdojo-api
  namespace: sketchdojo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sketchdojo-api
  template:
    metadata:
      labels:
        app: sketchdojo-api
    spec:
      containers:
      - name: api
        image: sketchdojo/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sketchdojo-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sketchdojo-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sketchdojo-secrets
              key: openai-api-key
        - name: STABILITY_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sketchdojo-secrets
              key: stability-ai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sketchdojo-api-service
  namespace: sketchdojo
spec:
  selector:
    app: sketchdojo-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
